services:
  bot:
    container_name: bhayanakbot
    tty: true
    image: ghcr.io/thehimanshushekhar/bhayanakbot:latest
    restart: always
    env_file:
      - ./src/.env
    ports:
      - 3999:3999
    volumes:
      - .:/app
