services:
  bot:
    container_name: bhayanakbot
    tty: true
    build:
      context: .
      dockerfile: dockerfile
    command: sh -c 'bun install && bun run dev'
    restart: always
    env_file:
      - ./src/.env
    ports:
      - 3999:3999
    volumes:
      - .:/app
