services:
  bot:
    container_name: bhayanakbot
    tty: true
    image: imbios/bun-node:latest
    command: sh -c 'git pull && bun install && bun run dev'
    restart: always
    env_file:
      - .env
    ports:
      - 3999:3999
    volumes:
      - .:/app
