version: "3"

services:
  bot:
    tty: true
    image: docker.io/bitnami/node:18-debian-11
    command: sh -c 'npm install && npm start'
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
  # mongo:
  #   tty: true
  #   image: docker.io/bitnami/mongodb:latest
  #   restart: always
  #   # volumes:
  #   #   - mongodb_data:/bitnami/mongodb
  #   ports:
  #     - 27017:27017
