export type QuestTemplate = {
	title: string;
	description: string;
	objectiveType: "work" | "crime" | "train";
	objectiveJob: string | null;
	objectiveCount: number;
	rewardCoins: number;
	rewardXp: number;
};

export const QUEST_TEMPLATES: QuestTemplate[] = [
	{
		title: "Gone Fishin'",
		description: "The lake isn't going to empty itself. Get out there.",
		objectiveType: "work",
		objectiveJob: "fishing",
		objectiveCount: 3,
		rewardCoins: 400,
		rewardXp: 100,
	},
	{
		title: "On the Clock",
		description: "Show up, do the work, get paid. Three times.",
		objectiveType: "work",
		objectiveJob: null,
		objectiveCount: 3,
		rewardCoins: 350,
		rewardXp: 80,
	},
	{
		title: "Hard Hat Required",
		description: "Someone has to build this city. Today that someone is you.",
		objectiveType: "work",
		objectiveJob: "construction",
		objectiveCount: 2,
		rewardCoins: 450,
		rewardXp: 120,
	},
	{
		title: "Rush Hour Hero",
		description: "The city's packages won't deliver themselves. Mostly.",
		objectiveType: "work",
		objectiveJob: "delivery_driver",
		objectiveCount: 3,
		rewardCoins: 380,
		rewardXp: 90,
	},
	{
		title: "Deep Cuts",
		description: "The mountain has secrets. Extract them.",
		objectiveType: "work",
		objectiveJob: "mining",
		objectiveCount: 2,
		rewardCoins: 500,
		rewardXp: 130,
	},
	{
		title: "Ship It",
		description: "Write code. Make it work. Don't think about it too hard.",
		objectiveType: "work",
		objectiveJob: "programmer",
		objectiveCount: 2,
		rewardCoins: 480,
		rewardXp: 110,
	},
	{
		title: "Order in the Court",
		description: "The jury is waiting. They've been waiting a while.",
		objectiveType: "work",
		objectiveJob: "lawyer",
		objectiveCount: 2,
		rewardCoins: 550,
		rewardXp: 140,
	},
	{
		title: "Crime Pays",
		description: "Allegedly. Commit any crime twice and find out.",
		objectiveType: "crime",
		objectiveJob: null,
		objectiveCount: 2,
		rewardCoins: 600,
		rewardXp: 150,
	},
	{
		title: "Light Fingers",
		description: "In and out. Leave no trace. Leave with their wallet.",
		objectiveType: "crime",
		objectiveJob: "pickpocket",
		objectiveCount: 3,
		rewardCoins: 500,
		rewardXp: 120,
	},
	{
		title: "Armed and Ambitious",
		description: "The vault won't open itself. Well, it will. You just need the right plan.",
		objectiveType: "crime",
		objectiveJob: "rob_bank",
		objectiveCount: 1,
		rewardCoins: 800,
		rewardXp: 200,
	},
	{
		title: "Taking from the Rich",
		description: "Find a target. Relieve them of their burden.",
		objectiveType: "crime",
		objectiveJob: "rob_player",
		objectiveCount: 2,
		rewardCoins: 550,
		rewardXp: 130,
	},
	{
		title: "Pump Iron",
		description: "The weights aren't going to lift themselves. Train strength twice.",
		objectiveType: "train",
		objectiveJob: null,
		objectiveCount: 2,
		rewardCoins: 300,
		rewardXp: 200,
	},
	{
		title: "Mind Over Matter",
		description: "Your brain is a muscle. Treat it like one.",
		objectiveType: "train",
		objectiveJob: null,
		objectiveCount: 3,
		rewardCoins: 350,
		rewardXp: 250,
	},
	{
		title: "Hustle Day",
		description: "Work hard, train hard. Do both.",
		objectiveType: "work",
		objectiveJob: null,
		objectiveCount: 2,
		rewardCoins: 400,
		rewardXp: 150,
	},
	{
		title: "The Patient Angler",
		description: "Five casts. Five chances. The fish are judging you.",
		objectiveType: "work",
		objectiveJob: "fishing",
		objectiveCount: 5,
		rewardCoins: 700,
		rewardXp: 180,
	},
];
